create_neo4j:
  activation: prelu
  alpha_l: 1
  attn_drop: 0.5
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0.0005
  feat_drop: 0.2
  feat_mask_rate: 0.5,0.005,0.8
  gpu: 0
  hidden_dim: 1024
  l2_coef: 0
  leave_unchanged: 0.3
  loss_fn: sce
  lr: 0.0008
  mae_epochs: 10000
  mask_rate: 0.4
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.1
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.7
  mp_edge_recon_loss_weight: 1
  mps_batch_size: 256
  mps_context_size: 3
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.001
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 3
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 4
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.2
  residual: false
  scheduler: true
  scheduler_gamma: 0.999
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true
